### PR TITLE
Update schemas

### LINKED ISSUE #7: `order` schema: `jsonschema.exceptions.ValidationError: 'admin_graphql_api_id' is a required property`
From [this Meltano Slack thread](https://meltano.slack.com/archives/C01TCRBBJD7/p1690837356838999?thread_ts=1690837356.838999&cid=C01TCRBBJD7):

```
 2023-08-01T16:22:27.657124Z [info     ] jsonschema.exceptions.ValidationError: 'admin_graphql_api_id' is a required property cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.657174Z [info     ]                                cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.657221Z [info     ] Failed validating 'required' in schema: cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.657269Z [info     ]     {'properties': {'id': {'type': 'integer'}, cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.657316Z [info     ]                     'updated_at': {'format': 'date-time', cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.657372Z [info     ]                                    'type': ['null', 'string']}}, cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.657419Z [info     ]      'required': ['admin_graphql_api_id', cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.657467Z [info     ]                   'body_html', cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.657513Z [info     ]                   'created_at', cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.657559Z [info     ]                   'handle',    cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.657605Z [info     ]                   'id',        cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.657651Z [info     ]                   'image',     cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.657700Z [info     ]                   'images',    cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.657745Z [info     ]                   'options',   cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.657790Z [info     ]                   'product_type', cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.657836Z [info     ]                   'published_at', cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.657883Z [info     ]                   'published_scope', cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.657928Z [info     ]                   'status',    cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.657975Z [info     ]                   'tags',      cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.658021Z [info     ]                   'template_suffix', cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.658066Z [info     ]                   'title',     cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.658216Z [info     ]                   'updated_at', cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.658271Z [info     ]                   'variants',  cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.658332Z [info     ]                   'vendor'],   cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.658380Z [info     ]      'type': 'object'}         cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.658427Z [info     ]                                cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.658475Z [info     ] On instance:                   cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
 2023-08-01T16:22:27.658521Z [info     ]     {'id': 6885950652493, 'updated_at': '2023-08-01T08:59:18-07:00'} cmd_type=loader name=target-parquet run_id=66f5f6a0-2e97-4673-94e5-53e67bd6b233 state_id=2023-08-01T162225--tap-shopify--target-parquet stdio=stderr
```

### LINKED ISSUE #8: jsonschema.exceptions.ValidationError on schema['properties']['billing_address']['properties']['address2']
Hi, 

I'm trying to run this tap with meltano. I have a problem with abandoned_checkouts and customers collections on address2 property.

It looks like the tap expects the field to be a string but in my case it contains a null value. 

here part of the error 

jsonschema.exceptions.ValidationError: None is not of type 'string'
Failed validating 'type' in schema['properties']['billing_address']['properties']['address2']
{'type': 'string'}
On instance['billing_address']['address2']
None

Do you know if I can do something on my side to avoid this, like adding some transformations, or it is a problem that should be address directly in the tap?

Thanks

### PR DESCRIPTION
**Pull request by ReubenFrankel**
Closes #7, closes #8

### CODE REVIEW

**Comment by konung** [comment]
Sorry. After 20th complaint from the import process - I just took a brute-force approach and did 4 glob replacements adding Null, Strings, and Objects everywhere. Those were the most common complaints.  Also a few Int complaints. 

I was just trying to get past the error on a dev system , to see if I would succeed.

**Comment by konung** [comment]
I can go ahead and test with new schema updates, if they are ready.

**Comment by konung** [comment]
Thanks @ReubenFrankel 


So tried to run it using default schema. Immediatly ran into problems


```log
2023-10-04T16:34:14.288303Z [info     ] 2023-10-04 11:34:14,288 | INFO     | tap-shopify          | Added 'inventory_items' as child stream to 'inventory_levels' cmd_type=elb consumer=False name=tap-shopify producer=True stdio=stderr string_id=tap-shopify
2023-10-04T16:34:14.288843Z [info     ] 2023-10-04 11:34:14,288 | INFO     | tap-shopify          | Added 'inventory_levels' as child stream to 'locations' cmd_type=elb consumer=False name=tap-shopify producer=True stdio=stderr string_id=tap-shopify
2023-10-04T16:34:14.289208Z [info     ] 2023-10-04 11:34:14,288 | INFO     | tap-shopify          | Added 'transactions' as child stream to 'orders' cmd_type=elb consumer=False name=tap-shopify producer=True stdio=stderr string_id=tap-shopify
2023-10-04T16:34:14.289683Z [info     ] 2023-10-04 11:34:14,288 | INFO     | tap-shopify          | Beginning incremental sync of 'abandoned_checkouts'... cmd_type=elb consumer=False name=tap-shopify producer=True stdio=stderr string_id=tap-shopify
2023-10-04T16:34:14.290003Z [info     ] 2023-10-04 11:34:14,288 | INFO     | tap-shopify          | Tap has custom mapper. Using 1 provided map(s). cmd_type=elb consumer=False name=tap-shopify producer=True stdio=stderr string_id=tap-shopify
2023-10-04T16:34:16.188464Z [info     ] 2023-10-04 11:34:16,188 | INFO     | singer_sdk.metrics   | METRIC: {"type": "timer", "metric": "http_request_duration", "value": 1.840916, "tags": {"stream": "abandoned_checkouts", "endpoint": "/checkouts.json", "http_status_code": 200, "status": "succeeded"}} cmd_type=elb consumer=False name=tap-shopify producer=True stdio=stderr string_id=tap-shopify
2023-10-04T16:34:16.217414Z [info     ] 2023-10-04 11:34:16,217 | WARNING  | tap-shopify          | Properties ('note_attributes', 'source_identifier', 'source_url', 'customer.last_order_id', 'customer.verified_email', 'customer.multipass_identifier', 'customer.tax_exempt', 'customer.last_order_name', 'customer.currency', 'customer.phone', 'customer.accepts_marketing_updated_at', 'customer.marketing_opt_in_level', 'customer.tax_exemptions', 'customer.email_marketing_consent', 'customer.sms_marketing_consent', 'customer.admin_graphql_api_id', 'customer.default_address', 'source', 'name', 'billing_address.latitude', 'billing_address.longitude') were present in the 'abandoned_checkouts' stream but not found in catalog schema. Ignoring. cmd_type=elb consumer=False name=tap-shopify producer=True stdio=stderr string_id=tap-shopify
2023-10-04T16:34:16.219222Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.219422Z [info     ]   File "/Users/konung/Projects/konungshop/Code/elt/konungshop-elt-meltano/konungshop-elt/.meltano/loaders/target-jsonl/venv/bin/target-jsonl", line 8, in <module> cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.219713Z [info     ] 2023-10-04 11:34:16,219 | WARNING  | tap-shopify          | Properties ('note_attributes', 'source_identifier', 'source_url', 'customer.last_order_id', 'customer.verified_email', 'customer.multipass_identifier', 'customer.tax_exempt', 'customer.last_order_name', 'customer.currency', 'customer.phone', 'customer.accepts_marketing_updated_at', 'customer.marketing_opt_in_level', 'customer.tax_exemptions', 'customer.email_marketing_consent', 'customer.sms_marketing_consent', 'customer.admin_graphql_api_id', 'customer.default_address', 'source', 'name') were present in the 'abandoned_checkouts' stream but not found in catalog schema. Ignoring. cmd_type=elb consumer=False name=tap-shopify producer=True stdio=stderr string_id=tap-shopify
2023-10-04T16:34:16.219993Z [info     ]     sys.exit(main())           cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.220134Z [info     ]   File "/Users/konung/Projects/konungshop/Code/elt/konungshop-elt-meltano/konungshop-elt/.meltano/loaders/target-jsonl/venv/lib/python3.10/site-packages/target_jsonl.py", line 92, in main cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.220393Z [info     ]     state = persist_messages(  cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.220594Z [info     ]   File "/Users/konung/Projects/konungshop/Code/elt/konungshop-elt-meltano/konungshop-elt/.meltano/loaders/target-jsonl/venv/lib/python3.10/site-packages/target_jsonl.py", line 54, in persist_messages cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.245416Z [info     ]     validators[o['stream']].validate((o['record'])) cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.245574Z [info     ]   File "/Users/konung/Projects/konungshop/Code/elt/konungshop-elt-meltano/konungshop-elt/.meltano/loaders/target-jsonl/venv/lib/python3.10/site-packages/jsonschema/validators.py", line 130, in validate cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.246197Z [info     ]     raise error                cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.246343Z [info     ] jsonschema.exceptions.ValidationError: '[]' is not of type 'array' cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.246528Z [info     ]                                cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.246667Z [info     ] Failed validating 'type' in schema['properties']['discount_codes']: cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.246789Z [info     ]     {'items': {'anyOf': [{'properties': {'discount_code': {'properties': {'code': {'type': ['string', cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.246913Z [info     ]                                                                                             'null']}, cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.247034Z [info     ]                                                                           'created_at': {'type': ['string', cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.247155Z [info     ]                                                                                                   'null']}, cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.247275Z [info     ]                                                                           'id': {'type': 'integer'}, cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.247395Z [info     ]                                                                           'updated_at': {'type': ['string', cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.247514Z [info     ]                                                                                                   'null']}, cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.247632Z [info     ]                                                                           'usage_count': {'type': 'integer'}}, cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.247752Z [info     ]                                                            'type': 'object'}}, cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.247872Z [info     ]                           'type': 'object'}]}, cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.248092Z [info     ]      'type': 'array'}          cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.248243Z [info     ]                                cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.248360Z [info     ] On instance['discount_codes']: cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.248831Z [info     ]     '[]'                       cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:34:16.588906Z [error    ] [Errno 32] Broken pipe         
Traceback (most recent call last):
  File "/Users/konung/.local/pipx/venvs/meltano/lib/python3.10/site-packages/meltano/core/logging/utils.py", line 199, in _write_line_writer
    await writer.drain()
  File "/Users/konung/.asdf/installs/python/3.10.13/lib/python3.10/asyncio/streams.py", line 371, in drain
    await self._protocol._drain_helper()
  File "/Users/konung/.asdf/installs/python/3.10.13/lib/python3.10/asyncio/streams.py", line 167, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/konung/.local/pipx/venvs/meltano/lib/python3.10/site-packages/meltano/core/logging/output_logger.py", line 207, in redirect_logging
    yield
  File "/Users/konung/.local/pipx/venvs/meltano/lib/python3.10/site-packages/meltano/core/block/extract_load.py", line 444, in run
    await self.run_with_job()
  File "/Users/konung/.local/pipx/venvs/meltano/lib/python3.10/site-packages/meltano/core/block/extract_load.py", line 476, in run_with_job
    await self.execute()
  File "/Users/konung/.local/pipx/venvs/meltano/lib/python3.10/site-packages/meltano/core/block/extract_load.py", line 436, in execute
    await manager.run()
  File "/Users/konung/.local/pipx/venvs/meltano/lib/python3.10/site-packages/meltano/core/block/extract_load.py", line 641, in run
    await self._wait_for_process_completion(self.elb.head)
  File "/Users/konung/.local/pipx/venvs/meltano/lib/python3.10/site-packages/meltano/core/block/extract_load.py", line 714, in _wait_for_process_completion
    raise output_futures_failed.exception()  # noqa: RSE102
  File "/Users/konung/.local/pipx/venvs/meltano/lib/python3.10/site-packages/meltano/core/logging/utils.py", line 233, in capture_subprocess_output
    if not await _write_line_writer(writer, line):
  File "/Users/konung/.local/pipx/venvs/meltano/lib/python3.10/site-packages/meltano/core/logging/utils.py", line 201, in _write_line_writer
    await writer.wait_closed()
  File "/Users/konung/.asdf/installs/python/3.10.13/lib/python3.10/asyncio/streams.py", line 343, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/Users/konung/.asdf/installs/python/3.10.13/lib/python3.10/asyncio/unix_events.py", line 676, in write
    n = os.write(self._fileno, data)
BrokenPipeError: [Errno 32] Broken pipe

```


I then proceeded and tried using my modified schema - and got much further along. THe reason I'm hitting validation schema errors with my "globbed" schema - is that I tried a bigger data sample - going back 30+ days. Simply haven't encountered these issues before. 


```log

2023-10-04T16:36:35.476236Z [info     ] 2023-10-04 11:36:35,475 | INFO     | singer_sdk.metrics   | METRIC: {"type": "timer", "metric": "sync_duration", "value": 0.17219901084899902, "tags": {"stream": "transactions", "context": {"order_id": 5080134221893}, "status": "succeeded"}} cmd_type=elb consumer=False name=tap-shopify producer=True stdio=stderr string_id=tap-shopify
2023-10-04T16:36:35.476434Z [info     ] 2023-10-04 11:36:35,475 | INFO     | singer_sdk.metrics   | METRIC: {"type": "counter", "metric": "record_count", "value": 0, "tags": {"stream": "transactions", "context": {"order_id": 5080134221893}}} cmd_type=elb consumer=False name=tap-shopify producer=True stdio=stderr string_id=tap-shopify
2023-10-04T16:36:35.478068Z [info     ] 2023-10-04 11:36:35,477 | INFO     | tap-shopify          | Beginning full_table sync of 'transactions' with context: {'order_id': 5080099225669}... cmd_type=elb consumer=False name=tap-shopify producer=True stdio=stderr string_id=tap-shopify
2023-10-04T16:36:35.478817Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:36:35.479029Z [info     ]   File "/Users/konung/Projects/konungshop/Code/elt/konungshop-elt-meltano/konungshop-elt/.meltano/loaders/target-jsonl/venv/bin/target-jsonl", line 8, in <module> cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:36:35.479384Z [info     ]     sys.exit(main())           cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:36:35.479620Z [info     ]   File "/Users/konung/Projects/konungshop/Code/elt/konungshop-elt-meltano/konungshop-elt/.meltano/loaders/target-jsonl/venv/lib/python3.10/site-packages/target_jsonl.py", line 92, in main cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:36:35.479813Z [info     ]     state = persist_messages(  cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:36:35.479996Z [info     ]   File "/Users/konung/Projects/konungshop/Code/elt/konungshop-elt-meltano/konungshop-elt/.meltano/loaders/target-jsonl/venv/lib/python3.10/site-packages/target_jsonl.py", line 54, in persist_messages cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:36:35.480178Z [info     ]     validators[o['stream']].validate((o['record'])) cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:36:35.480365Z [info     ]   File "/Users/konung/Projects/konungshop/Code/elt/konungshop-elt-meltano/konungshop-elt/.meltano/loaders/target-jsonl/venv/lib/python3.10/site-packages/jsonschema/validators.py", line 130, in validate cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:36:35.480661Z [info     ]     raise error                cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:36:35.480850Z [info     ] jsonschema.exceptions.ValidationError: 9 is not of type 'string', 'null' cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:36:35.481030Z [info     ]                                cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:36:35.481214Z [info     ] Failed validating 'type' in schema['properties']['device_id']: cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:36:35.481400Z [info     ]     {'type': ['string', 'null']} cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:36:35.481574Z [info     ]                                cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:36:35.481745Z [info     ] On instance['device_id']:      cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:36:35.481917Z [info     ]     9                          cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-10-04T16:36:35.512866Z [error    ] Loader failed
2023-10-04T16:36:35.513186Z [error    ] Block run completed.           block_type=ExtractLoadBlocks err=RunnerError('Loader failed') exit_codes={<PluginType.LOADERS: 'loaders'>: 1} set_number=0 success=False
```

**Comment by ReubenFrankel** [comment]
@konung Is it possible to share your modified schema?

**Comment by konung** [comment]
> @konung Is it possible to share your modified schema?
> 
> Also, out of curiosity, have you tried the [`singer-io` variant of `tap-shopify`](https://hub.meltano.com/extractors/tap-shopify--singer-io/)? If so, how far did you get with that?

1. Sure ( I changed ext to .TXT from .JSON, as github is not letting me attache JSON type files ) 
2. I tried . Also ran into an [issue there](https://github.com/sehnem/tap-shopify/issues/9).  ( Having said that , I was able to sync using 2 other tools
   a. Airbyte  (like actual airbyte , not Meltano addon) - it works but is very slow, and creates a ton of extra tables when flattening  ( which can be mitiagted via DBT scripts or simply SQL), but thats why I started looking for alternatives.   
   b. CloudQuery - works really well , but only syncs several tables. I don't know GO to be productive anought to quick fork & modify the Shopify Plugin. 
3. I really like that meltano has all the integrations I need in one place, but if not, I may settle on using multiple ELT tools.  ( which is fine too) 





   

[shopify.matatika.catalog.txt](https://github.com/Matatika/tap-shopify/files/12808994/shopify.matatika.catalog.txt)

**Comment by ReubenFrankel** [comment]
@konung Thanks. As you've probably noticed, this process is very much trial and error - especially for this volume of data (and even harder when we don't have access to it). Really appreciate your help here! :sweat_smile:

We are aiming for a release tomorrow (to resolve other issues), so I'm going to take a look at your schema and see if can reasonably merge them before then - if not then, of course, #12 can stay open.

**Comment by ReubenFrankel** [comment]
@konung Thanks. As you've probably noticed, this process is very much trial and error - especially for this volume of data (and even harder when we don't have access to it). Really appreciate your help here! :sweat_smile:

We are aiming for a release tomorrow (to resolve other issues), so I'm going to take a look at your schema and see if can reasonably merge with ours before then - if not then, of course, #12 can stay open.

**Pull request merged**
